# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a868873d4dbe02e76d402d98ca52c815d73f354fb85e4ea437a4d5100ba6188c17498e32160f717d998c2ab26ab7fff5e170e8cdbc19ff8b37fc585832aaa75

test:
  secret_key_base: a5aac45a527ca988bf02f6e3c6b23cc0866ca4862bb16ffce2a54403f715d4b12b13a740afe764aceafe6661e938b814977910b83195d7d025edc6f9919b0fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
